channels:
- conda-forge
dependencies:
- python=3.8.13
- pip<=22.2.2
- pip:
  - mlflow==2.11.1
  - cloudpickle==3.0.0
  - numpy==1.23.2
  - packaging==21.3
  - psutil==5.9.1
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.9.1
  - typing==3.7.4.3
name: mlflow-env
